---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    delay: 1
    exec_pre: apk add --no-cache fcgi
    exec_post: REQUEST_METHOD=GET cgi-fcgi -bind -connect localhost:9000

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: spritsail/php-fpm
    login: {from_secret: docker_login}
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 92ac2741604c4e2af49209f49d8e5fd1583a19155a8a85ea99bc57dd698df293

...
